Rapsys\BlogBundle\Entity\ArticleKeyword:
    type: entity
    table: articles_keywords
    id:
        article_id:
            type: integer
            options:
                unsigned: true
        keyword_id:
            type: integer
            options:
                unsigned: true
