Rapsys\BlogBundle\Entity\ArticleTranslation:
    type: entity
    repositoryClass: Rapsys\BlogBundle\Repository\ArticleTranslationRepository
    table: articles_translations
    id:
        article_id:
            type: integer
            options:
                unsigned: true
        locale:
            type: string
            length: 5
    fields:
        body:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        slug:
            type: string
            length: 128
            nullable: true
        title:
            type: string
            length: 128
            nullable: true
        created:
            type: datetime
        updated:
            type: datetime
    manyToOne:
        article:
            targetEntity: Rapsys\BlogBundle\Entity\Article
            inversedBy: article_translations
            joinColumn:
                nullable: false
    uniqueConstraints:
        locale_slug:
            columns: [ locale, slug ]
    lifecycleCallbacks:
        preUpdate: ['preUpdate']
