Rapsys\BlogBundle\Entity\AuthorTranslation:
        type: entity
        repositoryClass: Rapsys\BlogBundle\Repository\AuthorTranslationRepository
        table: authors_translations
        id:
                author_id:
                        type: smallint
                        options:
                                unsigned: true
                language_id:
                        type: smallint
                        options:
                                unsigned: true
        fields:
                description:
                        type: text
                created:
                        type: datetime
                updated:
                        type: datetime
        manyToOne:
                author:
                        targetEntity: Rapsys\BlogBundle\Entity\Author
                        inversedBy: author_translations
                language:
                        targetEntity: Rapsys\BlogBundle\Entity\Language
                        inversedBy: language_translations
