Rapsys\BlogBundle\Entity\Author:
    type: entity
    repositoryClass: Rapsys\BlogBundle\Repository\AuthorRepository
    table: authors
    indexes:
        name:
            columns: [ name ]
    id:
        id:
            type: smallint
            generator: 
                strategy: AUTO
            options:
                unsigned: true
    fields:
        name:
            type: string
            length: 64
        slug:
            type: string
            length: 64
            unique: true
        created:
            type: datetime
        updated:
            type: datetime
    oneToMany:
        articles:
            targetEntity: Rapsys\BlogBundle\Entity\Article
            mappedBy: author
        author_translations:
            targetEntity: Rapsys\BlogBundle\Entity\AuthorTranslation
            mappedBy: author
