Rapsys\BlogBundle\Entity\LanguageTranslation:
        type: entity
        repositoryClass: Rapsys\BlogBundle\Repository\LanguageTranslationRepository
        table: languages_translations
        id:
                language_id:
                        type: smallint
                        options:
                                unsigned: true
                target_id:
                        type: smallint
                        options:
                                unsigned: true
        fields:
                title:
                        type: string
                        length: 128
                created:
                        type: datetime
                updated:
                        type: datetime
        manyToOne:
                language:
                        targetEntity: Rapsys\BlogBundle\Entity\Language
                        inversedBy: language_translations
                target:
                        targetEntity: Rapsys\BlogBundle\Entity\Language
                        inversedBy: target_translations
