Rapsys\BlogBundle\Entity\SiteTranslation:
        type: entity
        repositoryClass: Rapsys\BlogBundle\Repository\SiteTranslationRepository
        table: sites_translations
        id:
                site_id:
                        type: smallint
                        options:
                                unsigned: true
                language_id:
                        type: smallint
                        options:
                                unsigned: true
        fields:
                title:
                        type: string
                        length: 128
                description:
                        type: text
                created:
                        type: datetime
                updated:
                        type: datetime
        manyToOne:
                site:
                        targetEntity: Rapsys\BlogBundle\Entity\Site
                        inversedBy: site_translations
                language:
                        targetEntity: Rapsys\BlogBundle\Entity\Language
                        inversedBy: site_translations
