Rapsys\BlogBundle\Entity\Site:
        type: entity
        repositoryClass: Rapsys\BlogBundle\Repository\SiteRepository
        table: sites
        indexes:
                domain:
                        columns: [ domain ]
        id:
                id:
                        type: smallint
                        generator: 
                                strategy: AUTO
                        options:
                                unsigned: true
        fields:
                domain:
                        type: string
                        length: 64
                created:
                        type: datetime
                updated:
                        type: datetime
        oneToMany:
                articles:
                        targetEntity: Rapsys\BlogBundle\Entity\Article
                        mappedBy: site
                site_translations:
                        targetEntity: Rapsys\BlogBundle\Entity\SiteTranslation
                        mappedBy: site
