root:
    path:     /
    defaults: { _controller: RapsysBlogBundle:Default:root }

homepage:
    path:     /{_locale}
    defaults: { _controller: RapsysBlogBundle:Page:index }
    requirements:
            _locale: '%blog.locales%'

about:
    path:     /{_locale}/about
    defaults: { _controller: RapsysBlogBundle:Page:about }
    requirements:
            _locale: '%blog.locales%'

contact:
    path:     /{_locale}/contact
    defaults: { _controller: RapsysBlogBundle:Page:contact }
    requirements:
            _locale: '%blog.locales%'

articles:
    path:     /{_locale}/articles
    defaults: { _controller: RapsysBlogBundle:Page:articleIndex }
    requirements:
            _locale: '%blog.locales%'

articles_article:
    path:     /{_locale}/articles/{_article}
    defaults: { _controller: RapsysBlogBundle:Page:articleRead }
    requirements:
            _locale: '%blog.locales%'
            #_article: '\d+'
            _article: '[a-z0-9-]+'

keywords:
    path:     /{_locale}/keywords
    defaults: { _controller: RapsysBlogBundle:Page:keywordIndex }
    requirements:
            _locale: '%blog.locales%'

keywords_keyword:
    path: /{_locale}/keywords/{_keyword}
    defaults: { _controller: RapsysBlogBundle:Page:keywordRead }
    requirements:
        _locale: '%blog.locales%'
        _keyword: '[a-z0-9-]+'
