<?php

namespace Rapsys\BlogBundle\Repository;

/**
 * ArticleTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
