<?php

namespace Rapsys\BlogBundle\Repository;

/**
 * KeywordTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
