<?php

namespace Rapsys\BlogBundle\Repository;

/**
 * SiteTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
